import type { DetailKey } from './types';

export type VisitTemplate = {
  templateId: string;
  department: string;
  product: string;
  patientGroup: string;
  detailAxis: string;
  doctorReaction: string;   // AI가 자유 생성 — 빈 문자열이면 AI가 직접 작성
  nextAxis: string;
  narrativeStyle: DetailKey['narrativeStyle'];
  exampleMemo: string;      // few-shot 예시 — AI에게 스타일 가이드로 전달
};

// ────────────────────────────────────────────────────────
// exampleMemo 작성 원칙:
//   - 100~200자, 영업사원이 폰으로 빠르게 타이핑한 현장 메모 스타일
//   - ~함, ~하심, ~예정, ~드림 종결 (습니다/볼예정/할예정 절대 금지)
//   - nextStrategy는 오늘 주제와 다른 각도 1개만
//   - doctorReaction은 매번 다르게 — 고정 패턴 없음
// ────────────────────────────────────────────────────────

const VISIT_TEMPLATES: VisitTemplate[] = [

  // ════════════════════════════════════════════════════
  // 위너프에이플러스 × 정형외과
  // ════════════════════════════════════════════════════
  {
    templateId: 'winuf-ortho-01',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: 'TKR·THR 직후 회복기 환자',
    detailAxis: '수술 후 단백 보충 속도와 회복 영향',
    doctorReaction: '',
    nextAxis: '실제 처방 흐름 및 반응 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '위너프에이플러스 TKR 후 단백 회복 속도 말씀드렸더니 관심 보이심. 기존 제품이랑 한번 비교해보겠다 하심. 다음엔 처방 시작하셨는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-02',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '수술 후 조기 재활 환자',
    detailAxis: '오메가3 조성과 수술 후 염증 반응 완화',
    doctorReaction: '',
    nextAxis: '재활 회복 경과 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '위너프에이플러스 오메가3 조성 재활 환자 적용 얘기 드림. 재활 빠른 케이스 있으면 한번 써볼 의향 보이심. 다음 방문 시 경과 확인할 예정',
  },
  {
    templateId: 'winuf-ortho-03',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '당뇨 합병 수술 환자',
    detailAxis: '수술 후 혈당 안정과 영양 공급 병행',
    doctorReaction: '',
    nextAxis: '혈당 관리 프로토콜 논의',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '위너프에이플러스 당뇨 합병 수술 환자 혈당 부담 낮다는 포인트 드렸더니 교수님 그 부분은 맞다고 하심. 다음엔 실제 혈당 관리 어떻게 하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-04',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '노인 수술 후 근육량 낮은 환자',
    detailAxis: '고령 환자 근감소 예방과 단백 공급',
    doctorReaction: '',
    nextAxis: '근력 회복 지표 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '고령 수술 환자 근육 회복에 위너프에이플러스 말씀드림. 어르신 환자 많다고 관심 보이시고 적용 고려해보겠다 하심. 다음 방문 때 근력 회복 케이스 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-ortho-05',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '수술 전 BMI·알부민 낮은 환자',
    detailAxis: '수술 전 영양 보강과 수술 결과 연관성',
    doctorReaction: '',
    nextAxis: '수술 전 처방 고려 여부',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '수술 전 영양 상태 안 좋은 환자 위너프에이플러스로 미리 잡는 얘기 드림. 그런 케이스 몇 명 있다고 하심. 다음엔 수술 전 처방 타이밍 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-06',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '기존 3챔버 TPN 사용 중인 중증 환자',
    detailAxis: '3챔버에서 4세대 위너프에이플러스 전환 타이밍',
    doctorReaction: '',
    nextAxis: '전환 사례 반응 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '위너프 쓰시는 중증 환자 위너프에이플러스 전환 얘기 꺼냄. 차이가 있냐고 물어보셔서 조성 설명드림. 다음에 전환해본 케이스 있으면 반응 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-07',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '심폐 문제로 수액 제한 필요한 환자',
    detailAxis: '수액 제한 상황에서 고농도 소량 투여 편의성',
    doctorReaction: '',
    nextAxis: '실제 적용 케이스 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '수액 제한 있는 환자 위너프에이플러스 소량 고농도 가능하다고 드렸더니 그 부분은 좋다고 하심. 실제 적용 케이스 있으면 다음에 확인할 예정',
  },
  {
    templateId: 'winuf-ortho-08',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '창상 치유 지연 위험 환자',
    detailAxis: '수술 후 창상 치유와 단백 공급 연관성',
    doctorReaction: '',
    nextAxis: '상처 회복 경과 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '위너프에이플러스 수술 후 상처 회복 단백 공급 얘기 드림. 지연 케이스 있어서 한번 써보겠다 하심. 다음엔 상처 경과 어떤지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-09',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '장기 TPN 필요 환자',
    detailAxis: '장기 TPN 환자 간 부담 최소화',
    doctorReaction: '',
    nextAxis: '간수치 변화 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '장기 영양 환자 간 부담 문제 꺼냄. 위너프에이플러스 간 부담 적다는 얘기에 관심 보이심. 다음엔 간수치 어떻게 보는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-10',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '대수술 후 ICU 입실 환자',
    detailAxis: '수술 전후 ICU 영양 공급 연속성',
    doctorReaction: '',
    nextAxis: 'ICU 처방 현황 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '대수술 ICU 환자 위너프에이플러스 연속 투여 얘기 드림. ICU팀이랑 같이 쓰는 경우 있다고 하심. 다음엔 ICU 처방 현황 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-11',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '다발성 수술·재수술 예정 환자',
    detailAxis: '반복 수술 환자 영양 누적 보충 전략',
    doctorReaction: '',
    nextAxis: '처방 지속 계획 논의',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '재수술 예정 환자 위너프에이플러스 미리 잡아두는 얘기 드림. 그런 환자 몇 명 있다고 하심. 다음엔 처방 타이밍 언제가 좋을지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-ortho-12',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '비만수술 후 영양 결핍 환자',
    detailAxis: '비만 수술 후 흡수 불량 영양 보완',
    doctorReaction: '',
    nextAxis: '영양 결핍 지표 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '비만수술 후 영양 결핍 환자 위너프에이플러스 얘기 드렸더니 그 파트는 내분비쪽이라고 하시면서도 관심 보이심. 다음엔 어떻게 쓰는지 더 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 위너프에이플러스 × 호흡기내과
  // ════════════════════════════════════════════════════
  {
    templateId: 'winuf-resp-01',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '식사량 저하와 체중 감소가 있는 호흡기 환자',
    detailAxis: '회복기 단백 보충과 저당질 영양 유지',
    doctorReaction: '',
    nextAxis: '영양 상태와 체중 변화 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '호흡기 환자 중 식사량 떨어지고 체중 빠지는 케이스에 위너프에이플러스 얘기 드렸더니 회복기 영양은 볼 수 있겠다고 하심. 다음엔 실제 적용 케이스 여쭤볼 예정',
  },
  {
    templateId: 'winuf-resp-02',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '폐렴 후 회복 중 환자',
    detailAxis: '폐렴 회복기 단백 보충과 회복 단축',
    doctorReaction: '',
    nextAxis: '회복 기간 변화 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '폐렴 회복기 위너프에이플러스 단백 보충 얘기 드림. 회복 느린 케이스에 써볼 수 있겠다 하심. 다음엔 회복 기간 달라지는지 확인할 예정',
  },
  {
    templateId: 'winuf-resp-03',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: 'CO2 retention 위험 환자',
    detailAxis: '고단백 저당질 조성과 CO2 부담 감소',
    doctorReaction: '',
    nextAxis: '호흡 부담 변화 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: 'CO2 잡아야 하는 환자에 위너프에이플러스 당질 부담 적다는 얘기 드림. 그 부분 중요하다고 하심. 다음엔 실제 호흡 부담 변화 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-resp-04',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '인공호흡기 이탈 환자',
    detailAxis: '기계호흡 이탈 후 영양 지원과 회복',
    doctorReaction: '',
    nextAxis: '이탈 성공률 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '기계호흡 이탈 환자 위너프에이플러스 영양 지원 얘기 드렸더니 ICU랑 연계해보겠다 하심. 다음엔 이탈 후 경과 어떤지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-resp-05',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '스테로이드 의존성 폐질환 환자',
    detailAxis: '스테로이드 장기 투여 근감소 예방',
    doctorReaction: '',
    nextAxis: '근육 보전 지표 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '스테로이드 오래 쓰는 환자 근감소 얘기 꺼냄. 위너프에이플러스 근육 보전 도움 된다고 드렸더니 관심 보이심. 다음엔 근육 지표 어떻게 보는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-resp-06',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '반복 입원 기관지확장증 환자',
    detailAxis: '기관지확장증 장기 영양 공급 전략',
    doctorReaction: '',
    nextAxis: '지속 처방 가능성 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '기관지확장증 반복 입원 환자 장기 영양 얘기 드림. 그런 환자 관리 어렵다고 하시면서 위너프에이플러스 한번 써보겠다 하심. 다음엔 지속 처방 가능한지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-resp-07',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '폐암 항암 진행 중 환자',
    detailAxis: '폐암 항암 중 영양 상태 유지',
    doctorReaction: '',
    nextAxis: '항암 중 처방 연계 방안 논의',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '폐암 항암 중 영양 유지 위너프에이플러스 얘기 드림. 항암 중에도 쓸 수 있냐고 물어보셔서 가능하다고 드렸더니 관심 보이심. 다음엔 처방 연계 어떻게 할지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 위너프에이플러스 × 외과
  // ════════════════════════════════════════════════════
  {
    templateId: 'winuf-surg-01',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '결장·직장 절제술 후 환자',
    detailAxis: '대장암 수술 후 회복기 영양 공급',
    doctorReaction: '',
    nextAxis: '처방 시작 타이밍 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '대장암 수술 후 위너프에이플러스 영양 공급 얘기 드렸더니 수술 직후 쓰는 것도 고려해보겠다 하심. 다음엔 처방 시작 타이밍 여쭤볼 예정',
  },
  {
    templateId: 'winuf-surg-02',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '간 부분 절제 후 환자',
    detailAxis: '간절제 후 간기능 회복과 영양 지원',
    doctorReaction: '',
    nextAxis: '간효소 수치 추이 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '간절제 후 위너프에이플러스 간 부담 적다는 얘기 드림. 수술 후 ALT 신경 쓴다고 하시면서 써볼 의향 보이심. 다음엔 수치 어떻게 바뀌는지 확인할 예정',
  },
  {
    templateId: 'winuf-surg-03',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '수술 전 항암 진행 중 환자',
    detailAxis: '수술 전 면역 영양 강화와 수술 결과',
    doctorReaction: '',
    nextAxis: '수술 전 처방 연계 논의',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '수술 전 항암 중인 환자 영양 상태 미리 챙기는 얘기 드림. 수술 전 컨디션이 회복에 영향 크다고 하시면서 관심 보이심. 다음엔 어떻게 연계할지 논의할 예정',
  },
  {
    templateId: 'winuf-surg-04',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '복막염 후 회복 중 환자',
    detailAxis: '복강 내 감염 회복기 단백 보충',
    doctorReaction: '',
    nextAxis: '회복 속도 차이 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '복막염 회복 환자 위너프에이플러스 단백 보충 얘기 드렸더니 항생제 끝난 후 영양이 문제라고 하심. 다음엔 실제 회복 빨라지는지 확인할 예정',
  },
  {
    templateId: 'winuf-surg-05',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '피판 이식·재건 수술 환자',
    detailAxis: '재건수술 후 조직 재생과 영양 지원',
    doctorReaction: '',
    nextAxis: '창상 치유 경과 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '재건수술 피판 환자 위너프에이플러스 조직 재생 얘기 드림. 그 환자들 영양이 관건이라고 하시면서 한번 써볼게 하심. 다음엔 창상 경과 어떤지 확인할 예정',
  },

  // ════════════════════════════════════════════════════
  // 위너프에이플러스 × 신경외과
  // ════════════════════════════════════════════════════
  {
    templateId: 'winuf-neuro-01',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '개두술 후 의식 회복기 환자',
    detailAxis: '개두술 후 단백 보충과 뇌 회복 영향',
    doctorReaction: '',
    nextAxis: '회복 경과 및 처방 흐름 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '위너프에이플러스 개두술 후 단백 보충 얘기 드렸더니 그 환자들 영양이 회복에 영향 크다고 하심. 다음엔 실제 처방 어떻게 하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-02',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '경구 불가 척추 수술 후 환자',
    detailAxis: '척추 수술 후 장기 TPN 영양 관리',
    doctorReaction: '',
    nextAxis: '경구 전환 전 영양 관리 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '척추 수술 후 경구 못 드시는 환자 위너프에이플러스 얘기 드림. 그런 환자 꽤 된다고 하심. 다음엔 경구 전환 전 얼마나 쓰는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-03',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '뇌졸중 후 재활 진행 환자',
    detailAxis: '뇌졸중 회복기 근감소 예방과 재활 성과',
    doctorReaction: '',
    nextAxis: '재활 성과와 영양 연관성 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '위너프에이플러스 뇌졸중 후 근감소 예방 얘기 드렸더니 재활 결과가 영양과 관계 있다고 하심. 다음엔 실제 적용 케이스 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-04',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '중증 두부 외상 ICU 환자',
    detailAxis: '두부 외상 환자 고단백 영양 공급 필요성',
    doctorReaction: '',
    nextAxis: '외상 후 영양 프로토콜 논의',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '두부 외상 환자 고단백 필요하다는 얘기에 위너프에이플러스 드림. 외상 ICU에서 영양이 중요하다고 하심. 다음엔 프로토콜 어떻게 하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-05',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '수술 전 영양불량 신경외과 환자',
    detailAxis: '수술 전 영양 상태 개선과 수술 결과 연관',
    doctorReaction: '',
    nextAxis: '수술 전 처방 루틴 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '신경외과 수술 전 영양 상태 얘기 꺼냄. 위너프에이플러스 미리 잡으면 수술 후 회복 다르다고 드렸더니 관심 보이심. 다음엔 처방 타이밍 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-06',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '장기 의식장애·식물상태 환자',
    detailAxis: '뇌수술 후 장기 의식장애 환자 영양 공급',
    doctorReaction: '',
    nextAxis: '장기 영양 공급 방식 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '장기 의식장애 환자 영양 위너프에이플러스 얘기 드렸더니 그런 환자 관리 복잡하다고 하심. 다음엔 현재 어떻게 공급하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-neuro-07',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '당뇨 합병 뇌·척추 수술 환자',
    detailAxis: '당뇨 합병 신경외과 환자 혈당 부담 감소',
    doctorReaction: '',
    nextAxis: '혈당 안정성 추이 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '당뇨 있는 신경외과 수술 환자 위너프에이플러스 혈당 부담 적다는 얘기 드렸더니 그 부분 신경 쓴다고 하심. 다음엔 실제 혈당 어떻게 나오는지 확인할 예정',
  },
  {
    templateId: 'winuf-neuro-08',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '간질지속증 후 중환자실 환자',
    detailAxis: '간질 발작 후 ICU 영양 지속 유지',
    doctorReaction: '',
    nextAxis: 'ICU 영양 관리 현황 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '간질 발작 후 중환자실 환자 위너프에이플러스 영양 유지 얘기 드림. 그런 케이스 영양 놓치기 쉽다고 하심. 다음엔 어떻게 관리하는지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 위너프에이플러스 × 중환자의학과
  // ════════════════════════════════════════════════════
  {
    templateId: 'winuf-icu-01',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '패혈증·패혈성 쇼크 환자',
    detailAxis: '패혈증 환자 고단백 영양 공급 전략',
    doctorReaction: '',
    nextAxis: '영양 공급 프로토콜 논의',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '패혈증 환자 고단백 공급 위너프에이플러스 얘기 드렸더니 패혈증에서 영양이 생존율 영향 준다고 하심. 다음엔 프로토콜 어떻게 쓰는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-icu-02',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '장기 기계호흡 중환자',
    detailAxis: '기계호흡 환자 CO2 부담 최소화 영양',
    doctorReaction: '',
    nextAxis: '호흡기 이탈 성공률 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '기계호흡 환자 위너프에이플러스 CO2 부담 적다는 얘기 드림. 이탈 시도할 때 영양도 신경 쓴다고 하심. 다음엔 이탈 성공 케이스에 영향 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-icu-03',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '폐부종·심부전 수액 제한 중환자',
    detailAxis: '수액 제한 중환자에서 고농도 소량 영양',
    doctorReaction: '',
    nextAxis: '수액 제한 상황 적용 현황 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '수액 제한 중환자 위너프에이플러스 소량 고농도 얘기 드렸더니 그런 환자 맞춤이라고 하심. 다음엔 실제 어떻게 적용하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-icu-04',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '당뇨 합병 중환자실 환자',
    detailAxis: '당뇨 합병 중증 환자 혈당 안정 영양',
    doctorReaction: '',
    nextAxis: '혈당 관리 방식 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '당뇨 중환자 위너프에이플러스 혈당 부담 낮다는 얘기 드렸더니 ICU 혈당 관리가 중요하다고 하심. 다음엔 실제 혈당 어떻게 나오는지 확인할 예정',
  },
  {
    templateId: 'winuf-icu-05',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '전신 염증 반응 SIRS 중환자',
    detailAxis: '오메가3 조성 전신 염증 반응 완화',
    doctorReaction: '',
    nextAxis: '염증 지표 변화 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '중환자 전신 염증 반응 위너프에이플러스 오메가3 얘기 드렸더니 SIRS 환자에 유용하겠다 하심. 다음엔 염증 수치 달라지는지 확인할 예정',
  },
  {
    templateId: 'winuf-icu-06',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '간부전·간경화 중환자',
    detailAxis: '간기능 저하 환자 간 부담 최소 영양',
    doctorReaction: '',
    nextAxis: '간수치 추이 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '간 안 좋은 중환자 위너프에이플러스 간 부담 적다는 얘기 드림. 그런 환자 영양 주기 조심스럽다고 하심. 다음엔 간수치 어떻게 보는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-icu-07',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '중증 다발성 외상 환자',
    detailAxis: '중증 외상 후 이화 대사 극복 고단백 영양',
    doctorReaction: '',
    nextAxis: '외상 후 영양 프로토콜 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '중증 외상 환자 이화 대사 위너프에이플러스 고단백 얘기 드렸더니 외상에서 영양이 생존 영향 크다고 하심. 다음엔 프로토콜 어떻게 하는지 여쭤볼 예정',
  },
  {
    templateId: 'winuf-icu-08',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '2주 이상 ICU 장기 재원 환자',
    detailAxis: '장기 ICU 재원 환자 근감소 예방',
    doctorReaction: '',
    nextAxis: '근육 보전 지표 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '장기 중환자실 환자 근감소 위너프에이플러스 얘기 드림. 오래 있는 환자 근육 빠지는 게 문제라고 하심. 다음엔 실제 적용 케이스 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 정형외과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-ortho-01',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '수술 전 빈혈 교정 필요 환자',
    detailAxis: '관절치환술 전 Hb 최적화',
    doctorReaction: '',
    nextAxis: '수술 전 처방 루틴 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '페린젝트 TKR 수술 전 Hb 미리 올리는 얘기 드렸더니 그게 말이 된다고 하심. 수술 전 처방 루틴으로 넣을지 다음 방문 때 얘기해볼 예정',
  },
  {
    templateId: 'ferr-ortho-02',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '수혈 거부 또는 저혈량 위험 환자',
    detailAxis: '수술 중 수혈 회피 전략',
    doctorReaction: '',
    nextAxis: '수혈 발생률 비교',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '수혈 거부 환자 페린젝트로 미리 챙기는 얘기 드림. 여호와의증인 환자 가끔 있다고 하시면서 써볼 의향 보이심. 다음엔 수혈 줄어드는지 확인할 예정',
  },
  {
    templateId: 'ferr-ortho-03',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '경구 복용 어렵거나 흡수 불량 환자',
    detailAxis: '경구 불내성 철 결핍 교정',
    doctorReaction: '',
    nextAxis: '전환 처방 여부 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '경구 철분제 못 드시는 환자 페린젝트 얘기 드렸더니 위장 장애로 못 먹는 환자 있다고 관심 보이심. 다음엔 실제 전환 처방해보셨는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-ortho-04',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '고령+만성 빈혈 환자',
    detailAxis: '고령 수술 전 철 보충과 준비',
    doctorReaction: '',
    nextAxis: '수술 준비 일정 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '고령 수술 환자 페린젝트 미리 잡아두는 얘기 드림. 어르신 환자 빈혈 많다고 하시면서 1회로 된다는 게 편하겠다 하심. 다음엔 처방 루틴 어떻게 할지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-ortho-05',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '수술 후 급격한 Hb 저하 환자',
    detailAxis: '수술 후 출혈 보충 속도',
    doctorReaction: '',
    nextAxis: 'Hb 회복 경과 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '수술 후 Hb 많이 떨어진 환자 페린젝트 보충 얘기 드렸더니 수혈 기준 근처 환자 있으면 써볼 수 있겠다 하심. 다음엔 Hb 회복 어떤지 확인할 예정',
  },
  {
    templateId: 'ferr-ortho-06',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '거동 불편한 외래 환자',
    detailAxis: '1회 투여 완결과 외래 내원 부담 감소',
    doctorReaction: '',
    nextAxis: '실제 적용 케이스 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '거동 불편한 환자 페린젝트 1회로 끝낼 수 있다는 얘기 드렸더니 그건 편하겠다 하심. 다음엔 실제 써보신 케이스 있는지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 신경외과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-neuro-01',
    department: '신경외과',
    product: '페린젝트',
    patientGroup: '수술 전 빈혈 신경외과 환자',
    detailAxis: '뇌수술 전 Hb 최적화',
    doctorReaction: '',
    nextAxis: '수술 전 처방 계획 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '신경외과 수술 전 Hb 올리는 페린젝트 얘기 드렸더니 수술 전 빈혈 신경 쓴다고 하심. 다음엔 처방 루틴 어떻게 할지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-neuro-02',
    department: '신경외과',
    product: '페린젝트',
    patientGroup: '수술 후 급격한 Hb 저하 환자',
    detailAxis: '척추 수술 출혈 후 빠른 Hb 보충',
    doctorReaction: '',
    nextAxis: 'Hb 회복 속도 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '척추 수술 후 Hb 많이 빠지는 케이스 페린젝트 얘기 드림. 수혈 기준 근처 환자 있으면 써볼 수 있겠다 하심. 다음엔 실제 회복 속도 여쭤볼 예정',
  },
  {
    templateId: 'ferr-neuro-03',
    department: '신경외과',
    product: '페린젝트',
    patientGroup: '의식장애로 경구 불가 환자',
    detailAxis: '경구 불가 환자 정맥 철분 보충',
    doctorReaction: '',
    nextAxis: '정맥 투여 처방 가능성 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '의식장애 환자 경구 철분 못 드시는 케이스 페린젝트 얘기 드렸더니 그런 환자 대안이 없었다고 하심. 다음엔 처방 넣어볼지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-neuro-04',
    department: '신경외과',
    product: '페린젝트',
    patientGroup: '재수술·반복 수술 예정 환자',
    detailAxis: '재수술 환자 반복 빈혈 지속 관리',
    doctorReaction: '',
    nextAxis: '지속 처방 주기 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '재수술 많은 환자 페린젝트 빈혈 지속 관리 얘기 드림. 그런 환자 빈혈 반복된다고 하심. 다음엔 처방 주기 어떻게 잡을지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 중환자의학과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-icu-01',
    department: '중환자의학과',
    product: '페린젝트',
    patientGroup: '수혈 위험 높은 중환자',
    detailAxis: '중환자 빈혈 수혈 회피 전략',
    doctorReaction: '',
    nextAxis: '수혈 없는 관리 가능 여부 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '중환자 빈혈 수혈 대신 페린젝트 얘기 드렸더니 수혈 최소화가 목표라고 하심. 다음엔 실제 어떻게 관리하는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-icu-02',
    department: '중환자의학과',
    product: '페린젝트',
    patientGroup: 'ESA 사용 중 철결핍 중환자',
    detailAxis: '패혈증 환자 ESA 반응 향상',
    doctorReaction: '',
    nextAxis: 'ESA 반응률 변화 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '패혈증 환자 ESA 써도 반응 없는 케이스 페린젝트 철분 같이 잡는 얘기 드림. 그 개념 맞다고 하심. 다음엔 실제 반응 달라지는지 확인할 예정',
  },
  {
    templateId: 'ferr-icu-03',
    department: '중환자의학과',
    product: '페린젝트',
    patientGroup: '수술 후 중환자실 입실 빈혈 환자',
    detailAxis: '수술 후 중환자 빠른 Hb 회복',
    doctorReaction: '',
    nextAxis: 'Hb 회복 속도 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '수술 후 중환자실 빈혈 환자 페린젝트 빠른 보충 얘기 드렸더니 1회로 된다는 게 편하겠다 하심. 다음엔 Hb 회복 얼마나 걸리는지 확인할 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 소화기내과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-gi-01',
    department: '소화기내과',
    product: '페린젝트',
    patientGroup: 'Crohn·UC 활성기 빈혈 환자',
    detailAxis: 'IBD 활성기 만성 빈혈 관리',
    doctorReaction: '',
    nextAxis: 'IBD 지속 처방 현황 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '크론 환자 페린젝트 빈혈 관리 얘기 드렸더니 IBD 환자 철분 경구로는 한계라고 하심. 현재 어떻게 관리하는지 다음엔 여쭤볼 예정',
  },
  {
    templateId: 'ferr-gi-02',
    department: '소화기내과',
    product: '페린젝트',
    patientGroup: '내시경 지혈 후 회복 환자',
    detailAxis: '소화관 출혈 후 철 보충',
    doctorReaction: '',
    nextAxis: '출혈 후 처방 타이밍 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '내시경 지혈 후 빈혈 환자 페린젝트 얘기 드림. 출혈 후 철 보충 루틴이 없다고 하시면서 관심 보이심. 다음엔 처방 타이밍 어떻게 잡는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-gi-03',
    department: '소화기내과',
    product: '페린젝트',
    patientGroup: '위암 절제 후 흡수 장애 환자',
    detailAxis: '위절제 후 흡수 불량 철 보충',
    doctorReaction: '',
    nextAxis: '지속 보충 주기 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '위절제 후 철분 흡수 안 되는 환자 페린젝트 얘기 드렸더니 그 환자들 빈혈 반복된다고 하심. 다음엔 보충 주기 어떻게 할지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 종양내과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-onco-01',
    department: '종양내과',
    product: '페린젝트',
    patientGroup: '항암 중 경구철분 흡수 불량 환자',
    detailAxis: '항암 중 햅시딘 상승 경구 흡수 저하 극복',
    doctorReaction: '',
    nextAxis: '헤모글로빈 회복 경과 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '항암 중 경구 철분 안 먹히는 환자 페린젝트 얘기 드렸더니 그 기전 알고 있다고 하심. 다음엔 실제 Hb 회복 경과 어떤지 확인할 예정',
  },
  {
    templateId: 'ferr-onco-02',
    department: '종양내과',
    product: '페린젝트',
    patientGroup: '급여 적용 가능 빈혈 환자',
    detailAxis: '급여 기준 환자 선별과 처방 효율화',
    doctorReaction: '',
    nextAxis: '급여 처방 비율 확인',
    narrativeStyle: '급여 기준 재확인형',
    exampleMemo: '페린젝트 급여 기준 얘기 드렸더니 기준이 까다롭다고 하심. 맞는 환자 골라드리는 게 중요할 것 같아 다음엔 그 부분 같이 확인해볼 예정',
  },
  {
    templateId: 'ferr-onco-03',
    department: '종양내과',
    product: '페린젝트',
    patientGroup: '수술 전 Hb 교정 필요 종양 환자',
    detailAxis: '수술 전 Hb 최적화로 수혈 회피',
    doctorReaction: '',
    nextAxis: '수혈 없는 수술 성공 여부 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '수술 전 Hb 올리려고 페린젝트 쓰는 얘기 드렸더니 수혈 줄이는 게 목표라고 하심. 다음엔 수술 전 처방 넣어봤는지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 산부인과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-obgyn-01',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '분만 후 출혈성 빈혈 환자',
    detailAxis: '분만 후 철 결핍 빠른 Hb 회복',
    doctorReaction: '',
    nextAxis: '분만 후 처방 루틴 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '분만 후 빈혈 환자 페린젝트 빠른 보충 얘기 드렸더니 경구로는 몇 주 걸린다고 하심. 1회 투여 괜찮다고 하셔서 다음엔 처방 루틴 넣을지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-02',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '임신 중 철 결핍 빈혈 환자',
    detailAxis: '임신 중 빈혈 안전한 철분 보충',
    doctorReaction: '',
    nextAxis: '임신 중 처방 주수 논의',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '임신 중 빈혈 환자 페린젝트 안전성 얘기 드렸더니 임신 중 철분제 처방 고민 많다고 하심. 다음엔 어느 주수부터 가능한지 같이 확인해볼 예정',
  },
  {
    templateId: 'ferr-obgyn-03',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '자궁근종 수술 전 빈혈 환자',
    detailAxis: '자궁근종 수술 전 Hb 최적화',
    doctorReaction: '',
    nextAxis: '수술 전 처방 계획 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '자궁근종 수술 전 Hb 올리는 거 페린젝트로 얘기 드림. 수술 전 빈혈 신경 많이 쓴다고 하시면서 관심 보이심. 다음엔 처방 타이밍 어떻게 할지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-04',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '반복 내원이 부담되는 산후 빈혈 환자',
    detailAxis: '1회 투여 완결성과 외래 재방문 부담 감소',
    doctorReaction: '',
    nextAxis: '산후 외래 처방 가능성 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '산후 빈혈 환자 반복 내원 부담 얘기 드렸더니 1회 투여는 편하겠다고 하심. 다음엔 실제 외래 처방 가능 케이스 있는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-05',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '철결핍이 뚜렷한 산모군',
    detailAxis: '경구용철분제 반응 부족 시 Hb 회복 속도',
    doctorReaction: '',
    nextAxis: '경구용철분제 전환 여부 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '산모군에서 경구용철분제 반응 늦는 케이스 페린젝트로 연결해 말씀드림. 그런 환자 있으면 보겠다고 하셔서 다음엔 전환 케이스 확인할 예정',
  },
  {
    templateId: 'ferr-obgyn-06',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '부인과 수술 예정 환자',
    detailAxis: '수술 전 Hb 교정과 출혈 부담 감소',
    doctorReaction: '',
    nextAxis: '수술 일정과 처방 타이밍 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '부인과 수술 전 Hb 교정 얘기 드렸더니 수술 일정 맞추는 게 중요하다고 하심. 다음엔 실제 처방 타이밍 어떻게 잡는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-07',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '분만 후 철결핍이 심한 산모',
    detailAxis: '산후 빠른 Hb 회복과 외래 재방문 감소',
    doctorReaction: '',
    nextAxis: '산후 회복 속도와 외래 편의성 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '분만 후 철결핍 심한 산모에 페린젝트 1회 보충 얘기 드렸더니 외래 재방문 줄일 수 있겠다고 하심. 다음엔 산후 회복 속도 실제로 어떤지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-08',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '임신 후기 철결핍 빈혈 산모',
    detailAxis: '임신 후기 Hb 보정과 분만 전 수혈 회피',
    doctorReaction: '',
    nextAxis: '분만 전 처방 주수 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '임신 후기 빈혈 산모에 페린젝트로 Hb 먼저 올리는 얘기 드림. 분만 전 수혈 부담 줄이는 게 좋겠다고 하심. 다음엔 어느 주수부터 보는지 여쭤볼 예정',
  },
  {
    templateId: 'ferr-obgyn-09',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '경구용철분제 복용이 어려운 산후 환자',
    detailAxis: '구역감이나 위장 불편으로 경구제 대체',
    doctorReaction: '',
    nextAxis: '경구 불내성 전환 사례 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '경구용철분제 먹기 힘든 산후 환자에 페린젝트 대안 얘기 드렸더니 그런 케이스는 있을 수 있다고 하심. 다음엔 전환 사례 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-obgyn-01',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '부인과 수술 후 식이 진행이 늦은 환자',
    detailAxis: '수술 후 단백 보충과 회복기 영양 유지',
    doctorReaction: '',
    nextAxis: '식이 재개 속도와 영양 반응 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '부인과 수술 후 식사 늦는 환자에 위너프에이플러스 단백 보충 얘기 드림. 회복기 환자에서는 볼 수 있겠다고 하셔서 다음엔 식이 재개 속도 여쭤볼 예정',
  },
  {
    templateId: 'winuf-obgyn-02',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '분만 후 회복기 영양 보충이 필요한 산모',
    detailAxis: '산후 회복기 아미노산 보충과 영양 유지',
    doctorReaction: '',
    nextAxis: '산후 영양 공급 반응 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '산후 회복기 산모에 위너프에이플러스 영양 보충 얘기 드렸더니 식사 진행 느린 산모는 있을 수 있다고 하심. 다음엔 실제 적용 케이스 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-obgyn-03',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '수액 제한이 필요한 수술 후 산모',
    detailAxis: '고농도 영양 공급과 삼투압 부담 차이',
    doctorReaction: '',
    nextAxis: '수술 후 적용 가능 여부 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '수액 많이 못 넣는 수술 후 산모에 위너프에이플러스 삼투압 차이 얘기 드렸더니 그 부분은 체크해보겠다고 하심. 다음엔 실제 적용 가능성 여쭤볼 예정',
  },
  {
    templateId: 'winuf-obgyn-04',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '산후 식이 지연과 체력 저하가 함께 있는 환자',
    detailAxis: '단백 보충과 회복기 에너지 유지',
    doctorReaction: '',
    nextAxis: '회복 속도와 처방 경험 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '산후 체력 떨어진 환자에 위너프에이플러스 단백 보충 얘기 드림. 회복기에는 볼 수 있겠다고 하심. 다음엔 처방 경험 있는지 확인할 예정',
  },
  {
    templateId: 'winuf-obgyn-05',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '제왕절개 후 금식이 길어진 산모',
    detailAxis: '수술 후 조기 영양 재개와 단백 보충',
    doctorReaction: '',
    nextAxis: '식이 재개 시점과 영양 흐름 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '제왕절개 후 금식 길어진 산모에 위너프에이플러스 얘기 드림. 회복기 영양은 볼 수 있겠다고 하셔서 다음엔 식이 재개 시점 여쭤볼 예정',
  },
  {
    templateId: 'winuf-obgyn-06',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '산후 체력 저하와 식사량 감소가 있는 산모',
    detailAxis: '회복기 에너지 유지와 아미노산 보충',
    doctorReaction: '',
    nextAxis: '산후 영양 유지 반응 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '산후 체력 저하 산모에 위너프에이플러스 아미노산 보충 얘기 드렸더니 식사 못 하는 경우는 있겠다고 하심. 다음엔 실제 적용 케이스 확인할 예정',
  },
  {
    templateId: 'winuf-obgyn-07',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '수액 제한이 필요한 부인과 수술 후 환자',
    detailAxis: '고농도 소량 영양과 수액 부담 차이',
    doctorReaction: '',
    nextAxis: '수술 후 적용 가능성 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '수액 제한 있는 부인과 수술 후 환자에 위너프에이플러스 얘기 드렸더니 삼투압 차이는 체크해보겠다고 하심. 다음엔 실제 적용 가능성 여쭤볼 예정',
  },
  {
    templateId: 'winuf-obgyn-08',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '장기 TPN을 고려하는 산부인과 환자',
    detailAxis: '기존 TPN 대비 아미노산과 포도당 조성 차이',
    doctorReaction: '',
    nextAxis: 'TPN 전환 흐름과 차이 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '장기 TPN 고려 산부인과 환자에 위너프에이플러스 조성 차이 얘기 드림. 기존 TPN에서 비교해볼 수 있겠다고 하셔서 다음엔 전환 흐름 확인할 예정',
  },

  // ════════════════════════════════════════════════════
  // 페린젝트 × 신장내과
  // ════════════════════════════════════════════════════
  {
    templateId: 'ferr-nephro-01',
    department: '신장내과',
    product: '페린젝트',
    patientGroup: 'ESA 병용 철 결핍 CKD 환자',
    detailAxis: 'CKD 환자 ESA 반응률 향상',
    doctorReaction: '',
    nextAxis: 'ESA 반응률 변화 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '신부전 환자 ESA 반응 잘 안 되는 케이스 페린젝트 얘기 드렸더니 철분 같이 잡아야 한다고 하심. 다음엔 ESA 반응 달라지는지 확인할 예정',
  },
  {
    templateId: 'ferr-nephro-02',
    department: '신장내과',
    product: '페린젝트',
    patientGroup: '혈액투석 중 빈혈 환자',
    detailAxis: '투석 환자 철 보충 편의성',
    doctorReaction: '',
    nextAxis: '투석 중 투여 가능 여부 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '투석 환자 페린젝트 투석 중 투여 가능하다는 얘기 드렸더니 번거로움 줄어든다고 하심. 다음엔 실제 적용 케이스 있는지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 플라주OP × 마취과
  // ════════════════════════════════════════════════════
  {
    templateId: 'plaju-anes-01',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '저혈압 위험 고령·허약 환자',
    detailAxis: '전신마취 유도 중 저혈압 예방',
    doctorReaction: '',
    nextAxis: '수술별 사용 현황 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '플라주OP 마취 유도 중 혈압 안정 얘기 드렸더니 고령 환자 혈압 잡는 게 항상 신경 쓰인다고 하심. 다음엔 실제 어떤 케이스에 쓰는지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-anes-02',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '외래 당일 수술 환자',
    detailAxis: '당일 수술 빠른 회복과 병상 회전',
    doctorReaction: '',
    nextAxis: '회복실 체류 시간 비교',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '플라주OP 당일 수술 환자 빠른 회복 얘기 드렸더니 회복실 병상 회전이 중요하다고 하심. 다음엔 체류 시간 달라지는지 확인할 예정',
  },
  {
    templateId: 'plaju-anes-03',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '진정 깊이 조절 필요 환자',
    detailAxis: '제이세덱스 대비 부작용 프로파일',
    doctorReaction: '',
    nextAxis: '활성화 부작용 발생률 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '플라주OP 제이세덱스 대비 부작용 얘기 드렸더니 활성화 부작용 신경 쓴다고 하심. 다음엔 실제 비교 경험 있으신지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-anes-04',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '소아 전신마취 케이스',
    detailAxis: '소아 마취 용량 편의성',
    doctorReaction: '',
    nextAxis: '용량 조절 실제 경험 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '소아 마취 플라주OP 용량 편의성 얘기 드렸더니 소아 케이스 용량 잡기 늘 까다롭다고 하심. 다음엔 실제 써보신 경험 있으신지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-anes-05',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '저환기 위험 COPD·비만 환자',
    detailAxis: '호흡 억제 최소화 마취 안전성',
    doctorReaction: '',
    nextAxis: '회복실 산소 요구 변화 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '비만이나 COPD 환자 마취 후 호흡 억제 플라주OP 얘기 드렸더니 그게 항상 걱정이라고 하심. 다음엔 산소 요구 얼마나 달라지는지 확인할 예정',
  },
  {
    templateId: 'plaju-anes-06',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '오피오이드 부작용 이력 환자',
    detailAxis: '오피오이드 절약 효과',
    doctorReaction: '',
    nextAxis: '통증 관리 병용 프로토콜 논의',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '오피오이드 부작용 있었던 환자 플라주OP 병용 얘기 드렸더니 줄일 수 있으면 좋겠다고 하심. 다음엔 실제 프로토콜 어떻게 하는지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-anes-07',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '심혈관 기저질환 환자',
    detailAxis: '심혈관 예비능 낮은 환자 마취 안전성',
    doctorReaction: '',
    nextAxis: '심전도 변화 관찰 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '심장 약한 환자 마취 플라주OP 안전성 얘기 드렸더니 그 환자들 항상 긴장된다고 하심. 다음엔 실제 심전도 어떻게 나오는지 확인할 예정',
  },
  {
    templateId: 'plaju-anes-08',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '즉각 마취 필요 응급 케이스',
    detailAxis: '응급 수술 신속 마취 유도',
    doctorReaction: '',
    nextAxis: '응급 도입 가능성 논의',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '응급 수술 빠른 마취 유도 플라주OP 얘기 드렸더니 응급에서 시간이 중요하다고 하심. 다음엔 응급실 도입 가능한지 여쭤볼 예정',
  },

  // ════════════════════════════════════════════════════
  // 플라주OP × 응급의학과
  // ════════════════════════════════════════════════════
  {
    templateId: 'plaju-er-01',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '다발성 외상 응급 환자',
    detailAxis: '외상 쇼크 초기 진정',
    doctorReaction: '',
    nextAxis: '응급 진정 프로토콜 적용 논의',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '다발 외상 초기 진정 플라주OP 얘기 드렸더니 외상에서 빠른 진정이 핵심이라고 하심. 다음엔 실제 프로토콜에 넣을 수 있는지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-er-02',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '즉각 삽관 필요 환자',
    detailAxis: '응급 기도 확보 시 진정',
    doctorReaction: '',
    nextAxis: 'RSI 보조 사용 경험 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '응급 삽관 플라주OP 진정 얘기 드렸더니 RSI에 뭘 쓰는지 고민한다고 하심. 다음엔 실제 써봤는지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-er-03',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '처치 협조 불가 환자',
    detailAxis: '절차 진정 통증 유발 처치 보조',
    doctorReaction: '',
    nextAxis: '절차 진정 만족도 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '처치 중 진정 필요한 환자 플라주OP 얘기 드렸더니 그런 케이스 꽤 있다고 하심. 다음엔 실제 써봤을 때 만족도 어떤지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-er-04',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '다약제 복용 고령 응급 환자',
    detailAxis: '고령 응급 환자 과진정 회피',
    doctorReaction: '',
    nextAxis: '과진정 없는 경험 공유',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '고령 응급 환자 진정 플라주OP 안전성 얘기 드렸더니 어르신은 항상 조심스럽다고 하심. 다음엔 과진정 없었던 경험 있으신지 여쭤볼 예정',
  },
  {
    templateId: 'plaju-er-05',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '알코올 금단·중증 섬망 환자',
    detailAxis: '중증 섬망 진정 유지',
    doctorReaction: '',
    nextAxis: '섬망 억제 효과 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '알코올 금단 섬망 환자 플라주OP 진정 얘기 드렸더니 그런 환자 잡는 게 어렵다고 하심. 다음엔 효과 있었는지 여쭤볼 예정',
  },
];

const EXTRA_VISIT_TEMPLATES: VisitTemplate[] = [
  {
    templateId: 'extra-ortho-01',
    department: '정형외과',
    product: '페린젝트',
    patientGroup: '수술 전 빈혈이 뚜렷한 관절 치환 예정 환자',
    detailAxis: '수술 전 Hb 교정과 수혈 회피',
    doctorReaction: '',
    nextAxis: '수술 일정과 처방 타이밍 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '관절 치환 수술 전 빈혈 환자 페린젝트 얘기 드렸더니 수술 전 Hb가 중요하다고 하심. 다음엔 실제 처방 타이밍 여쭤볼 예정',
  },
  {
    templateId: 'extra-ortho-02',
    department: '정형외과',
    product: '위너프에이플러스',
    patientGroup: '재활 초기에 식사량이 떨어진 환자',
    detailAxis: '회복기 단백 보충과 재활 속도',
    doctorReaction: '',
    nextAxis: '재활 경과와 영양 반응 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '재활 초기에 식사량 떨어지는 환자 위너프에이플러스 얘기 드림. 회복기엔 볼 수 있겠다고 하셔서 다음엔 재활 경과 여쭤볼 예정',
  },
  {
    templateId: 'extra-resp-01',
    department: '호흡기내과',
    product: '위너프에이플러스',
    patientGroup: '호흡 재활 중 식이량 저하 환자',
    detailAxis: '단백 보충과 호흡 재활 회복',
    doctorReaction: '',
    nextAxis: '재활 병행 환자 반응 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '호흡 재활 환자에 위너프에이플러스 단백 보충 얘기 드렸더니 영양 상태가 중요하다고 하심. 다음엔 실제 적용 케이스 여쭤볼 예정',
  },
  {
    templateId: 'extra-resp-02',
    department: '호흡기내과',
    product: '페린젝트',
    patientGroup: '폐렴 후 빈혈이 오래 가는 환자',
    detailAxis: '경구용철분제 반응이 더딘 외래 빈혈',
    doctorReaction: '',
    nextAxis: 'Hb 회복 속도와 처방 흐름 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '폐렴 후 빈혈이 길어지는 환자 페린젝트 얘기 드림. 경구로는 더딜 수 있다고 하셔서 다음엔 Hb 회복 속도 여쭤볼 예정',
  },
  {
    templateId: 'extra-surg-01',
    department: '외과',
    product: '페린젝트',
    patientGroup: '복부 수술 전 철결핍 빈혈 환자',
    detailAxis: '수술 전 철 보충과 수혈 부담 감소',
    doctorReaction: '',
    nextAxis: '수술 전 처방 적합성 확인',
    narrativeStyle: '급여 기준 재확인형',
    exampleMemo: '복부 수술 전 빈혈 환자 페린젝트 얘기 드렸더니 수혈 부담 줄이는 게 좋겠다고 하심. 다음엔 급여 기준 맞는지 확인할 예정',
  },
  {
    templateId: 'extra-surg-02',
    department: '외과',
    product: '위너프에이플러스',
    patientGroup: '장기 금식 후 경구 재개가 늦는 환자',
    detailAxis: '수술 후 회복기 단백과 열량 보충',
    doctorReaction: '',
    nextAxis: '식이 재개 시점 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '장기 금식 후 식사 늦는 환자 위너프에이플러스 얘기 드림. 회복기엔 쓸 수 있겠다고 하셔서 다음엔 식이 재개 시점 여쭤볼 예정',
  },
  {
    templateId: 'extra-neuro-01',
    department: '신경외과',
    product: '페린젝트',
    patientGroup: '뇌수술 전 빈혈 교정이 필요한 환자',
    detailAxis: '수술 전 Hb 보정과 수혈 회피',
    doctorReaction: '',
    nextAxis: '수술 전후 빈혈 관리 흐름 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '뇌수술 전 빈혈 환자 페린젝트 얘기 드렸더니 수혈 줄이는 게 중요하다고 하심. 다음엔 실제 수술 전 처방 흐름 여쭤볼 예정',
  },
  {
    templateId: 'extra-neuro-02',
    department: '신경외과',
    product: '위너프에이플러스',
    patientGroup: '장기 재원 중 식사량이 부족한 환자',
    detailAxis: '장기 입원 환자 단백 보충과 회복 유지',
    doctorReaction: '',
    nextAxis: '재원 기간 중 영양 반응 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '장기 재원 중 식사 부족한 환자 위너프에이플러스 얘기 드렸더니 영양이 빠지면 회복이 늦는다고 하심. 다음엔 실제 반응 여쭤볼 예정',
  },
  {
    templateId: 'extra-icu-01',
    department: '중환자의학과',
    product: '위너프에이플러스',
    patientGroup: '중증 패혈증 회복기 환자',
    detailAxis: '고단백 영양과 회복기 에너지 공급',
    doctorReaction: '',
    nextAxis: 'ICU 영양 프로토콜 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '패혈증 회복기 환자 위너프에이플러스 얘기 드렸더니 중환자 영양이 중요하다고 하심. 다음엔 ICU 프로토콜에 들어가는지 여쭤볼 예정',
  },
  {
    templateId: 'extra-icu-02',
    department: '중환자의학과',
    product: '페린젝트',
    patientGroup: 'ICU 재원 중 철결핍 빈혈 환자',
    detailAxis: '수혈 부담을 줄이는 정맥 철 보충',
    doctorReaction: '',
    nextAxis: '중환자실 적용 경험 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: 'ICU 빈혈 환자 페린젝트 얘기 드렸더니 수혈 부담 줄일 수 있으면 좋겠다고 하심. 다음엔 실제 중환자실 적용 경험 여쭤볼 예정',
  },
  {
    templateId: 'extra-gi-01',
    department: '소화기내과',
    product: '위너프에이플러스',
    patientGroup: 'IBD 악화로 식사량이 줄어든 환자',
    detailAxis: '장관 영양 부담과 단백 보충',
    doctorReaction: '',
    nextAxis: '식사량 저하 환자 반응 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: 'IBD 악화로 식사량 줄어든 환자 위너프에이플러스 얘기 드렸더니 영양이 먼저라고 하심. 다음엔 실제 반응 여쭤볼 예정',
  },
  {
    templateId: 'extra-gi-02',
    department: '소화기내과',
    product: '페린젝트',
    patientGroup: '위장관 출혈 후 경구용철분제 반응이 약한 환자',
    detailAxis: '빠른 Hb 회복과 외래 추적 편의성',
    doctorReaction: '',
    nextAxis: '출혈 후 처방 루틴 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '위장관 출혈 후 빈혈 환자 페린젝트 얘기 드렸더니 경구로는 더딜 수 있다고 하심. 다음엔 외래 루틴 어떻게 잡는지 여쭤볼 예정',
  },
  {
    templateId: 'extra-onco-01',
    department: '종양내과',
    product: '페린젝트',
    patientGroup: '항암 후 피로가 심한 빈혈 환자',
    detailAxis: 'Hb 회복과 외래 재방문 부담 감소',
    doctorReaction: '',
    nextAxis: '항암 후 적용 환자군 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '항암 후 피로 심한 빈혈 환자 페린젝트 얘기 드렸더니 외래 재방문 적은 게 좋겠다고 하심. 다음엔 실제 적용 환자군 여쭤볼 예정',
  },
  {
    templateId: 'extra-onco-02',
    department: '종양내과',
    product: '위너프에이플러스',
    patientGroup: '암 수술 후 식사량 저하 환자',
    detailAxis: '회복기 단백 보충과 에너지 유지',
    doctorReaction: '',
    nextAxis: '수술 후 영양 반응 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '암 수술 후 식사량 떨어진 환자 위너프에이플러스 얘기 드림. 회복기에는 의미 있겠다고 하셔서 다음엔 실제 반응 여쭤볼 예정',
  },
  {
    templateId: 'extra-obgyn-01',
    department: '산부인과',
    product: '페린젝트',
    patientGroup: '산후 회복 중 경구용철분제 반응이 더딘 산모',
    detailAxis: '1회 투여와 빠른 Hb 회복',
    doctorReaction: '',
    nextAxis: '산후 외래 처방 흐름 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '산후 회복 중 경구용철분제 반응 늦는 산모 페린젝트 얘기 드렸더니 1회 투여는 편하겠다고 하심. 다음엔 외래 처방 가능성 확인할 예정',
  },
  {
    templateId: 'extra-obgyn-02',
    department: '산부인과',
    product: '위너프에이플러스',
    patientGroup: '분만 후 식이 진행이 늦은 산모',
    detailAxis: '단백 보충과 회복기 영양 유지',
    doctorReaction: '',
    nextAxis: '식이 재개와 영양 반응 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '분만 후 식이 진행 늦은 산모에 위너프에이플러스 얘기 드림. 회복기 영양은 볼 수 있겠다고 하셔서 다음엔 실제 적용 여부 여쭤볼 예정',
  },
  {
    templateId: 'extra-nephro-01',
    department: '신장내과',
    product: '페린젝트',
    patientGroup: 'CKD 외래에서 피로가 심한 철결핍 환자',
    detailAxis: 'ESA 병용 전 철 보충과 Hb 반응',
    doctorReaction: '',
    nextAxis: 'ESA 반응과 철 지표 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: 'CKD 외래 피로 심한 철결핍 환자 페린젝트 얘기 드렸더니 철분 보충이 먼저라고 하심. 다음엔 ESA 반응 같이 볼지 여쭤볼 예정',
  },
  {
    templateId: 'extra-nephro-02',
    department: '신장내과',
    product: '페린젝트',
    patientGroup: '투석 환자 중 외래 내원이 부담되는 환자',
    detailAxis: '반복 내원 부담 감소와 철 보충 편의성',
    doctorReaction: '',
    nextAxis: '투석실 적용 가능성 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '투석 환자 내원 부담 큰 케이스 페린젝트 얘기 드렸더니 편의성은 좋겠다고 하심. 다음엔 투석실에서 실제 쓰는지 여쭤볼 예정',
  },
  {
    templateId: 'extra-anes-01',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '수술 후 회복실 체류 시간이 긴 환자',
    detailAxis: '회복실 회전과 진정 깊이 조절',
    doctorReaction: '',
    nextAxis: '회복실 사용 흐름 확인',
    narrativeStyle: '지난 방문 확인형',
    exampleMemo: '회복실 체류 긴 환자 플라주OP 얘기 드렸더니 회복실 회전이 중요하다고 하심. 다음엔 실제 사용 흐름 여쭤볼 예정',
  },
  {
    templateId: 'extra-anes-02',
    department: '마취과',
    product: '플라주OP',
    patientGroup: '고령·허약으로 과진정 우려가 있는 환자',
    detailAxis: '과진정 회피와 안전한 마취 유도',
    doctorReaction: '',
    nextAxis: '고령 환자 사용 경험 확인',
    narrativeStyle: '교수 질문 답변형',
    exampleMemo: '고령 허약 환자 마취 플라주OP 얘기 드렸더니 과진정은 항상 조심한다고 하심. 다음엔 실제 사용 경험 여쭤볼 예정',
  },
  {
    templateId: 'extra-er-01',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '즉시 처치가 필요한 협조 불가 환자',
    detailAxis: '짧은 처치 시간 진정 보조',
    doctorReaction: '',
    nextAxis: '응급 처치 프로토콜 확인',
    narrativeStyle: '처방 경험 확인형',
    exampleMemo: '협조 어려운 응급 환자 플라주OP 얘기 드렸더니 처치 시간 줄이는 게 중요하다고 하심. 다음엔 실제 프로토콜에 넣는지 여쭤볼 예정',
  },
  {
    templateId: 'extra-er-02',
    department: '응급의학과',
    product: '플라주OP',
    patientGroup: '응급 삽관 전 진정이 필요한 환자',
    detailAxis: '기도 확보 전 진정 안정성',
    doctorReaction: '',
    nextAxis: 'RSI 보조 경험 확인',
    narrativeStyle: '환자 케이스 연결형',
    exampleMemo: '응급 삽관 전 진정 플라주OP 얘기 드렸더니 RSI에서 뭘 쓰는지 고민하신다고 하심. 다음엔 실제 보조 경험 여쭤볼 예정',
  },
];

function departmentMatches(templateDepartment: string, department: string): boolean {
  if (templateDepartment === '공통') return true;
  const compactTemplate = templateDepartment.replace(/\s+/g, '');
  const compactDepartment = department.replace(/\s+/g, '');
  return compactDepartment.includes(compactTemplate) || compactTemplate.includes(compactDepartment);
}

export function getVisitTemplates(department: string, products: string[]): VisitTemplate[] {
  const normalizedProducts = products.length > 0 ? products : ['위너프에이플러스', '페린젝트'];
  return [...VISIT_TEMPLATES, ...EXTRA_VISIT_TEMPLATES].filter(
    (template) =>
      normalizedProducts.includes(template.product) &&
      departmentMatches(template.department, department)
  );
}

export function getVisitTemplateById(templateId: string): VisitTemplate | undefined {
  return [...VISIT_TEMPLATES, ...EXTRA_VISIT_TEMPLATES].find((template) => template.templateId === templateId);
}

export function getAllVisitTemplates(): VisitTemplate[] {
  return [...VISIT_TEMPLATES, ...EXTRA_VISIT_TEMPLATES];
}
